---
version: 0.0.{build}
image:
  - Ubuntu1804
environment:
  SONAR_LOGIN:
    secure: bnQUNyXHBXRKsEgv6khzKvz0llHlf3w7eaX1FiD9Qr9rVrzh2z5qYTv8d4qtMVjv
before_build:
  - dotnet restore
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet tool install --global coverlet.console
  - find tests -type f -name "*.csproj" -exec dotnet add {} package coverlet.msbuild \;
build_script:
  - dotnet sonarscanner begin /k:"coryjthompson_TaskPrincess" /d:"sonar.host.url=https://sonarcloud.io" /o:"coryjthompson" /d:"sonar.login=$SONAR_LOGIN" /d:sonar.cs.opencover.reportsPaths=tests/CoverageResults/coverage.opencover.xml /d:sonar.coverage.exclusions="**Test*.cs"
  - dotnet build
test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutput=../CoverageResults/ /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat=\"opencover,json\" -m:1
  - dotnet sonarscanner end /d:"sonar.login=$SONAR_LOGIN"
