//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Filter.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TaskPrincess.FilterDsl.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class FilterParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, DOT=3, STRING=4, INT=5, DOUBLE=6, UUID=7, AND=8, OR=9, 
		XOR=10, COLON=11, NOT=12, BEFORE=13, AFTER=14, NONE=15, ANY=16, MEQUALS=17, 
		ISNT=18, HAS=19, HASNT=20, STARTS_WITH=21, ENDS_WITH=22, MWORD=23, NO_WORD=24, 
		LESS_THAN_OR_EQUAL_TO=25, GREATER_THAN_OR_EQUAL_TO=26, LESS_THAN=27, GREATER_THAN=28, 
		NOT_EQUAL=29, EQUALS=30, TAG=31, DAY_MONDAY=32, DAY_TUESDAY=33, DAY_WEDNESDAY=34, 
		DAY_THURSDAY=35, DAY_FRIDAY=36, DAY_SATURDAY=37, DAY_SUNDAY=38, DAY_ORDINAL=39, 
		WEEK_SOCW=40, WEEK_EOCW=41, WEEK_SOW=42, WEEK_EOW=43, WEEK_SOWW=44, WEEK_EOWW=45, 
		WEEK_SOD=46, WEEK_EOD=47, WEEK_YESTERDAY=48, WEEK_TODAY=49, WEEK_NOW=50, 
		WEEK_TOMORROW=51, MONTH_JANUARY=52, MONTH_FEBUARY=53, MONTH_MARCH=54, 
		MONTH_APRIL=55, MONTH_MAY=56, MONTH_JUNE=57, MONTH_JULY=58, MONTH_AUGUST=59, 
		MONTH_SEPTEMBER=60, MONTH_OCTOBER=61, MONTH_NOVEMBER=62, MONTH_DECEMBER=63, 
		DATE_CALC_LATER=64, REGEX=65, WORD=66, WHITESPACE=67;
	public const int
		RULE_query = 0, RULE_expression = 1, RULE_filter_id = 2, RULE_filter_tags = 3, 
		RULE_predicate = 4, RULE_binary_operator = 5, RULE_relational_operator = 6, 
		RULE_constant = 7, RULE_value = 8, RULE_property_modifier = 9, RULE_date = 10, 
		RULE_date_day = 11, RULE_date_week = 12, RULE_date_month = 13, RULE_date_calc = 14, 
		RULE_property = 15;
	public static readonly string[] ruleNames = {
		"query", "expression", "filter_id", "filter_tags", "predicate", "binary_operator", 
		"relational_operator", "constant", "value", "property_modifier", "date", 
		"date_day", "date_week", "date_month", "date_calc", "property"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'.'", null, null, null, null, null, null, null, "':'", 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "'<='", "'>='", "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "DOT", "STRING", "INT", "DOUBLE", "UUID", "AND", "OR", 
		"XOR", "COLON", "NOT", "BEFORE", "AFTER", "NONE", "ANY", "MEQUALS", "ISNT", 
		"HAS", "HASNT", "STARTS_WITH", "ENDS_WITH", "MWORD", "NO_WORD", "LESS_THAN_OR_EQUAL_TO", 
		"GREATER_THAN_OR_EQUAL_TO", "LESS_THAN", "GREATER_THAN", "NOT_EQUAL", 
		"EQUALS", "TAG", "DAY_MONDAY", "DAY_TUESDAY", "DAY_WEDNESDAY", "DAY_THURSDAY", 
		"DAY_FRIDAY", "DAY_SATURDAY", "DAY_SUNDAY", "DAY_ORDINAL", "WEEK_SOCW", 
		"WEEK_EOCW", "WEEK_SOW", "WEEK_EOW", "WEEK_SOWW", "WEEK_EOWW", "WEEK_SOD", 
		"WEEK_EOD", "WEEK_YESTERDAY", "WEEK_TODAY", "WEEK_NOW", "WEEK_TOMORROW", 
		"MONTH_JANUARY", "MONTH_FEBUARY", "MONTH_MARCH", "MONTH_APRIL", "MONTH_MAY", 
		"MONTH_JUNE", "MONTH_JULY", "MONTH_AUGUST", "MONTH_SEPTEMBER", "MONTH_OCTOBER", 
		"MONTH_NOVEMBER", "MONTH_DECEMBER", "DATE_CALC_LATER", "REGEX", "WORD", 
		"WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Filter.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static FilterParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FilterParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FilterParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class QueryContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32; expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParenthesesExpressionContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ParenthesesExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenthesesExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FilterIdExpressionContext : ExpressionContext {
		public Filter_idContext filter_id() {
			return GetRuleContext<Filter_idContext>(0);
		}
		public FilterIdExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilterIdExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryExpressionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Binary_operatorContext binary_operator() {
			return GetRuleContext<Binary_operatorContext>(0);
		}
		public BinaryExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PredicateExpressionContext : ExpressionContext {
		public PredicateContext predicate() {
			return GetRuleContext<PredicateContext>(0);
		}
		public PredicateExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicateExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FilterTagsExpressionContext : ExpressionContext {
		public Filter_tagsContext filter_tags() {
			return GetRuleContext<Filter_tagsContext>(0);
		}
		public FilterTagsExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilterTagsExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WORD:
				{
				_localctx = new PredicateExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 35; predicate();
				}
				break;
			case INT:
			case UUID:
				{
				_localctx = new FilterIdExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 36; filter_id();
				}
				break;
			case TAG:
				{
				_localctx = new FilterTagsExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 37; filter_tags();
				}
				break;
			case T__0:
				{
				_localctx = new ParenthesesExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 38; Match(T__0);
				State = 39; expression(0);
				State = 40; Match(T__1);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 51;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BinaryExpressionContext(new ExpressionContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_expression);
					State = 44;
					if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
					State = 46;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << AND) | (1L << OR) | (1L << XOR))) != 0)) {
						{
						State = 45; binary_operator();
						}
					}

					State = 48; expression(6);
					}
					} 
				}
				State = 53;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Filter_idContext : ParserRuleContext {
		public ITerminalNode UUID() { return GetToken(FilterParser.UUID, 0); }
		public ITerminalNode INT() { return GetToken(FilterParser.INT, 0); }
		public Filter_idContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_filter_id; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilter_id(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Filter_idContext filter_id() {
		Filter_idContext _localctx = new Filter_idContext(Context, State);
		EnterRule(_localctx, 4, RULE_filter_id);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			_la = TokenStream.LA(1);
			if ( !(_la==INT || _la==UUID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Filter_tagsContext : ParserRuleContext {
		public ITerminalNode TAG() { return GetToken(FilterParser.TAG, 0); }
		public Filter_tagsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_filter_tags; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilter_tags(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Filter_tagsContext filter_tags() {
		Filter_tagsContext _localctx = new Filter_tagsContext(Context, State);
		EnterRule(_localctx, 6, RULE_filter_tags);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56; Match(TAG);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicateContext : ParserRuleContext {
		public PropertyContext property() {
			return GetRuleContext<PropertyContext>(0);
		}
		public ITerminalNode COLON() { return GetToken(FilterParser.COLON, 0); }
		public ITerminalNode DOT() { return GetToken(FilterParser.DOT, 0); }
		public Property_modifierContext property_modifier() {
			return GetRuleContext<Property_modifierContext>(0);
		}
		public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		public Relational_operatorContext relational_operator() {
			return GetRuleContext<Relational_operatorContext>(0);
		}
		public PredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PredicateContext predicate() {
		PredicateContext _localctx = new PredicateContext(Context, State);
		EnterRule(_localctx, 8, RULE_predicate);
		int _la;
		try {
			State = 71;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 58; property();
				State = 61;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==DOT) {
					{
					State = 59; Match(DOT);
					State = 60; property_modifier();
					}
				}

				State = 63; Match(COLON);
				State = 65;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
				case 1:
					{
					State = 64; constant();
					}
					break;
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 67; property();
				State = 68; relational_operator();
				State = 69; constant();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Binary_operatorContext : ParserRuleContext {
		public ITerminalNode AND() { return GetToken(FilterParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(FilterParser.OR, 0); }
		public ITerminalNode XOR() { return GetToken(FilterParser.XOR, 0); }
		public Binary_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binary_operator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinary_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Binary_operatorContext binary_operator() {
		Binary_operatorContext _localctx = new Binary_operatorContext(Context, State);
		EnterRule(_localctx, 10, RULE_binary_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << AND) | (1L << OR) | (1L << XOR))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Relational_operatorContext : ParserRuleContext {
		public ITerminalNode LESS_THAN_OR_EQUAL_TO() { return GetToken(FilterParser.LESS_THAN_OR_EQUAL_TO, 0); }
		public ITerminalNode GREATER_THAN_OR_EQUAL_TO() { return GetToken(FilterParser.GREATER_THAN_OR_EQUAL_TO, 0); }
		public ITerminalNode LESS_THAN() { return GetToken(FilterParser.LESS_THAN, 0); }
		public ITerminalNode GREATER_THAN() { return GetToken(FilterParser.GREATER_THAN, 0); }
		public ITerminalNode NOT_EQUAL() { return GetToken(FilterParser.NOT_EQUAL, 0); }
		public ITerminalNode EQUALS() { return GetToken(FilterParser.EQUALS, 0); }
		public Relational_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relational_operator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelational_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Relational_operatorContext relational_operator() {
		Relational_operatorContext _localctx = new Relational_operatorContext(Context, State);
		EnterRule(_localctx, 12, RULE_relational_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LESS_THAN_OR_EQUAL_TO) | (1L << GREATER_THAN_OR_EQUAL_TO) | (1L << LESS_THAN) | (1L << GREATER_THAN) | (1L << NOT_EQUAL) | (1L << EQUALS))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ConstantContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstant(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstantContext constant() {
		ConstantContext _localctx = new ConstantContext(Context, State);
		EnterRule(_localctx, 14, RULE_constant);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
	 
		public ValueContext() { }
		public virtual void CopyFrom(ValueContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DoubleValueContext : ValueContext {
		public ITerminalNode DOUBLE() { return GetToken(FilterParser.DOUBLE, 0); }
		public DoubleValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDoubleValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DateValueContext : ValueContext {
		public DateContext date() {
			return GetRuleContext<DateContext>(0);
		}
		public DateValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDateValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntegerValueContext : ValueContext {
		public ITerminalNode INT() { return GetToken(FilterParser.INT, 0); }
		public IntegerValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntegerValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UuidValueContext : ValueContext {
		public ITerminalNode UUID() { return GetToken(FilterParser.UUID, 0); }
		public UuidValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUuidValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RegexValueContext : ValueContext {
		public ITerminalNode REGEX() { return GetToken(FilterParser.REGEX, 0); }
		public RegexValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRegexValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LiteralStringValueContext : ValueContext {
		public ITerminalNode STRING() { return GetToken(FilterParser.STRING, 0); }
		public LiteralStringValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralStringValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringValueContext : ValueContext {
		public ITerminalNode WORD() { return GetToken(FilterParser.WORD, 0); }
		public StringValueContext(ValueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 16, RULE_value);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new IntegerValueContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 79; Match(INT);
				}
				break;
			case DOUBLE:
				_localctx = new DoubleValueContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 80; Match(DOUBLE);
				}
				break;
			case STRING:
				_localctx = new LiteralStringValueContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 81; Match(STRING);
				}
				break;
			case REGEX:
				_localctx = new RegexValueContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 82; Match(REGEX);
				}
				break;
			case UUID:
				_localctx = new UuidValueContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 83; Match(UUID);
				}
				break;
			case DAY_MONDAY:
			case DAY_TUESDAY:
			case DAY_WEDNESDAY:
			case DAY_THURSDAY:
			case DAY_FRIDAY:
			case DAY_SATURDAY:
			case DAY_SUNDAY:
			case DAY_ORDINAL:
			case WEEK_SOCW:
			case WEEK_EOCW:
			case WEEK_SOW:
			case WEEK_EOW:
			case WEEK_SOWW:
			case WEEK_EOWW:
			case WEEK_SOD:
			case WEEK_EOD:
			case WEEK_YESTERDAY:
			case WEEK_TODAY:
			case WEEK_NOW:
			case WEEK_TOMORROW:
			case MONTH_JANUARY:
			case MONTH_FEBUARY:
			case MONTH_MARCH:
			case MONTH_APRIL:
			case MONTH_MAY:
			case MONTH_JUNE:
			case MONTH_JULY:
			case MONTH_AUGUST:
			case MONTH_SEPTEMBER:
			case MONTH_OCTOBER:
			case MONTH_NOVEMBER:
			case MONTH_DECEMBER:
			case DATE_CALC_LATER:
				_localctx = new DateValueContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 84; date();
				}
				break;
			case WORD:
				_localctx = new StringValueContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 85; Match(WORD);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Property_modifierContext : ParserRuleContext {
		public ITerminalNode NOT() { return GetToken(FilterParser.NOT, 0); }
		public ITerminalNode BEFORE() { return GetToken(FilterParser.BEFORE, 0); }
		public ITerminalNode AFTER() { return GetToken(FilterParser.AFTER, 0); }
		public ITerminalNode NONE() { return GetToken(FilterParser.NONE, 0); }
		public ITerminalNode ANY() { return GetToken(FilterParser.ANY, 0); }
		public ITerminalNode MEQUALS() { return GetToken(FilterParser.MEQUALS, 0); }
		public ITerminalNode ISNT() { return GetToken(FilterParser.ISNT, 0); }
		public ITerminalNode HAS() { return GetToken(FilterParser.HAS, 0); }
		public ITerminalNode HASNT() { return GetToken(FilterParser.HASNT, 0); }
		public ITerminalNode STARTS_WITH() { return GetToken(FilterParser.STARTS_WITH, 0); }
		public ITerminalNode ENDS_WITH() { return GetToken(FilterParser.ENDS_WITH, 0); }
		public ITerminalNode MWORD() { return GetToken(FilterParser.MWORD, 0); }
		public ITerminalNode NO_WORD() { return GetToken(FilterParser.NO_WORD, 0); }
		public Property_modifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_property_modifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProperty_modifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Property_modifierContext property_modifier() {
		Property_modifierContext _localctx = new Property_modifierContext(Context, State);
		EnterRule(_localctx, 18, RULE_property_modifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NOT) | (1L << BEFORE) | (1L << AFTER) | (1L << NONE) | (1L << ANY) | (1L << MEQUALS) | (1L << ISNT) | (1L << HAS) | (1L << HASNT) | (1L << STARTS_WITH) | (1L << ENDS_WITH) | (1L << MWORD) | (1L << NO_WORD))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DateContext : ParserRuleContext {
		public Date_dayContext date_day() {
			return GetRuleContext<Date_dayContext>(0);
		}
		public Date_weekContext date_week() {
			return GetRuleContext<Date_weekContext>(0);
		}
		public Date_monthContext date_month() {
			return GetRuleContext<Date_monthContext>(0);
		}
		public Date_calcContext date_calc() {
			return GetRuleContext<Date_calcContext>(0);
		}
		public DateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DateContext date() {
		DateContext _localctx = new DateContext(Context, State);
		EnterRule(_localctx, 20, RULE_date);
		try {
			State = 94;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DAY_MONDAY:
			case DAY_TUESDAY:
			case DAY_WEDNESDAY:
			case DAY_THURSDAY:
			case DAY_FRIDAY:
			case DAY_SATURDAY:
			case DAY_SUNDAY:
			case DAY_ORDINAL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 90; date_day();
				}
				break;
			case WEEK_SOCW:
			case WEEK_EOCW:
			case WEEK_SOW:
			case WEEK_EOW:
			case WEEK_SOWW:
			case WEEK_EOWW:
			case WEEK_SOD:
			case WEEK_EOD:
			case WEEK_YESTERDAY:
			case WEEK_TODAY:
			case WEEK_NOW:
			case WEEK_TOMORROW:
				EnterOuterAlt(_localctx, 2);
				{
				State = 91; date_week();
				}
				break;
			case MONTH_JANUARY:
			case MONTH_FEBUARY:
			case MONTH_MARCH:
			case MONTH_APRIL:
			case MONTH_MAY:
			case MONTH_JUNE:
			case MONTH_JULY:
			case MONTH_AUGUST:
			case MONTH_SEPTEMBER:
			case MONTH_OCTOBER:
			case MONTH_NOVEMBER:
			case MONTH_DECEMBER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 92; date_month();
				}
				break;
			case DATE_CALC_LATER:
				EnterOuterAlt(_localctx, 4);
				{
				State = 93; date_calc();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Date_dayContext : ParserRuleContext {
		public ITerminalNode DAY_MONDAY() { return GetToken(FilterParser.DAY_MONDAY, 0); }
		public ITerminalNode DAY_TUESDAY() { return GetToken(FilterParser.DAY_TUESDAY, 0); }
		public ITerminalNode DAY_WEDNESDAY() { return GetToken(FilterParser.DAY_WEDNESDAY, 0); }
		public ITerminalNode DAY_THURSDAY() { return GetToken(FilterParser.DAY_THURSDAY, 0); }
		public ITerminalNode DAY_FRIDAY() { return GetToken(FilterParser.DAY_FRIDAY, 0); }
		public ITerminalNode DAY_SATURDAY() { return GetToken(FilterParser.DAY_SATURDAY, 0); }
		public ITerminalNode DAY_SUNDAY() { return GetToken(FilterParser.DAY_SUNDAY, 0); }
		public ITerminalNode DAY_ORDINAL() { return GetToken(FilterParser.DAY_ORDINAL, 0); }
		public Date_dayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date_day; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate_day(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Date_dayContext date_day() {
		Date_dayContext _localctx = new Date_dayContext(Context, State);
		EnterRule(_localctx, 22, RULE_date_day);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DAY_MONDAY) | (1L << DAY_TUESDAY) | (1L << DAY_WEDNESDAY) | (1L << DAY_THURSDAY) | (1L << DAY_FRIDAY) | (1L << DAY_SATURDAY) | (1L << DAY_SUNDAY) | (1L << DAY_ORDINAL))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Date_weekContext : ParserRuleContext {
		public ITerminalNode WEEK_SOCW() { return GetToken(FilterParser.WEEK_SOCW, 0); }
		public ITerminalNode WEEK_EOCW() { return GetToken(FilterParser.WEEK_EOCW, 0); }
		public ITerminalNode WEEK_SOW() { return GetToken(FilterParser.WEEK_SOW, 0); }
		public ITerminalNode WEEK_EOW() { return GetToken(FilterParser.WEEK_EOW, 0); }
		public ITerminalNode WEEK_SOWW() { return GetToken(FilterParser.WEEK_SOWW, 0); }
		public ITerminalNode WEEK_EOWW() { return GetToken(FilterParser.WEEK_EOWW, 0); }
		public ITerminalNode WEEK_SOD() { return GetToken(FilterParser.WEEK_SOD, 0); }
		public ITerminalNode WEEK_EOD() { return GetToken(FilterParser.WEEK_EOD, 0); }
		public ITerminalNode WEEK_YESTERDAY() { return GetToken(FilterParser.WEEK_YESTERDAY, 0); }
		public ITerminalNode WEEK_TODAY() { return GetToken(FilterParser.WEEK_TODAY, 0); }
		public ITerminalNode WEEK_NOW() { return GetToken(FilterParser.WEEK_NOW, 0); }
		public ITerminalNode WEEK_TOMORROW() { return GetToken(FilterParser.WEEK_TOMORROW, 0); }
		public Date_weekContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date_week; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate_week(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Date_weekContext date_week() {
		Date_weekContext _localctx = new Date_weekContext(Context, State);
		EnterRule(_localctx, 24, RULE_date_week);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << WEEK_SOCW) | (1L << WEEK_EOCW) | (1L << WEEK_SOW) | (1L << WEEK_EOW) | (1L << WEEK_SOWW) | (1L << WEEK_EOWW) | (1L << WEEK_SOD) | (1L << WEEK_EOD) | (1L << WEEK_YESTERDAY) | (1L << WEEK_TODAY) | (1L << WEEK_NOW) | (1L << WEEK_TOMORROW))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Date_monthContext : ParserRuleContext {
		public ITerminalNode MONTH_JANUARY() { return GetToken(FilterParser.MONTH_JANUARY, 0); }
		public ITerminalNode MONTH_FEBUARY() { return GetToken(FilterParser.MONTH_FEBUARY, 0); }
		public ITerminalNode MONTH_MARCH() { return GetToken(FilterParser.MONTH_MARCH, 0); }
		public ITerminalNode MONTH_APRIL() { return GetToken(FilterParser.MONTH_APRIL, 0); }
		public ITerminalNode MONTH_MAY() { return GetToken(FilterParser.MONTH_MAY, 0); }
		public ITerminalNode MONTH_JUNE() { return GetToken(FilterParser.MONTH_JUNE, 0); }
		public ITerminalNode MONTH_JULY() { return GetToken(FilterParser.MONTH_JULY, 0); }
		public ITerminalNode MONTH_AUGUST() { return GetToken(FilterParser.MONTH_AUGUST, 0); }
		public ITerminalNode MONTH_SEPTEMBER() { return GetToken(FilterParser.MONTH_SEPTEMBER, 0); }
		public ITerminalNode MONTH_OCTOBER() { return GetToken(FilterParser.MONTH_OCTOBER, 0); }
		public ITerminalNode MONTH_NOVEMBER() { return GetToken(FilterParser.MONTH_NOVEMBER, 0); }
		public ITerminalNode MONTH_DECEMBER() { return GetToken(FilterParser.MONTH_DECEMBER, 0); }
		public Date_monthContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date_month; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate_month(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Date_monthContext date_month() {
		Date_monthContext _localctx = new Date_monthContext(Context, State);
		EnterRule(_localctx, 26, RULE_date_month);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MONTH_JANUARY) | (1L << MONTH_FEBUARY) | (1L << MONTH_MARCH) | (1L << MONTH_APRIL) | (1L << MONTH_MAY) | (1L << MONTH_JUNE) | (1L << MONTH_JULY) | (1L << MONTH_AUGUST) | (1L << MONTH_SEPTEMBER) | (1L << MONTH_OCTOBER) | (1L << MONTH_NOVEMBER) | (1L << MONTH_DECEMBER))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Date_calcContext : ParserRuleContext {
		public ITerminalNode DATE_CALC_LATER() { return GetToken(FilterParser.DATE_CALC_LATER, 0); }
		public Date_calcContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date_calc; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate_calc(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Date_calcContext date_calc() {
		Date_calcContext _localctx = new Date_calcContext(Context, State);
		EnterRule(_localctx, 28, RULE_date_calc);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(DATE_CALC_LATER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyContext : ParserRuleContext {
		public ITerminalNode WORD() { return GetToken(FilterParser.WORD, 0); }
		public PropertyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_property; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFilterVisitor<TResult> typedVisitor = visitor as IFilterVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProperty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyContext property() {
		PropertyContext _localctx = new PropertyContext(Context, State);
		EnterRule(_localctx, 30, RULE_property);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; Match(WORD);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x45', 'm', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '-', '\n', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x31', '\n', '\x3', '\x3', '\x3', '\a', '\x3', '\x34', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x37', '\v', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x5', '\x6', '@', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', '\x44', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x5', '\x6', 'J', '\n', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x5', '\n', 'Y', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', '\x61', '\n', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x2', '\x3', '\x4', '\x12', '\x2', '\x4', '\x6', '\b', '\n', 
		'\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', 
		' ', '\x2', '\t', '\x4', '\x2', '\a', '\a', '\t', '\t', '\x3', '\x2', 
		'\n', '\f', '\x3', '\x2', '\x1B', ' ', '\x3', '\x2', '\xE', '\x1A', '\x3', 
		'\x2', '\"', ')', '\x3', '\x2', '*', '\x35', '\x3', '\x2', '\x36', '\x41', 
		'\x2', 'm', '\x2', '\"', '\x3', '\x2', '\x2', '\x2', '\x4', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '\x38', '\x3', '\x2', '\x2', '\x2', '\b', 
		':', '\x3', '\x2', '\x2', '\x2', '\n', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'K', '\x3', '\x2', '\x2', '\x2', '\xE', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'O', '\x3', '\x2', '\x2', '\x2', '\x12', 'X', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'Z', '\x3', '\x2', '\x2', '\x2', '\x16', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x62', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', 'h', '\x3', '\x2', '\x2', '\x2', ' ', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\"', '#', '\x5', '\x4', '\x3', '\x2', '#', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '$', '%', '\b', '\x3', '\x1', '\x2', '%', '-', '\x5', 
		'\n', '\x6', '\x2', '&', '-', '\x5', '\x6', '\x4', '\x2', '\'', '-', '\x5', 
		'\b', '\x5', '\x2', '(', ')', '\a', '\x3', '\x2', '\x2', ')', '*', '\x5', 
		'\x4', '\x3', '\x2', '*', '+', '\a', '\x4', '\x2', '\x2', '+', '-', '\x3', 
		'\x2', '\x2', '\x2', ',', '$', '\x3', '\x2', '\x2', '\x2', ',', '&', '\x3', 
		'\x2', '\x2', '\x2', ',', '\'', '\x3', '\x2', '\x2', '\x2', ',', '(', 
		'\x3', '\x2', '\x2', '\x2', '-', '\x35', '\x3', '\x2', '\x2', '\x2', '.', 
		'\x30', '\f', '\a', '\x2', '\x2', '/', '\x31', '\x5', '\f', '\a', '\x2', 
		'\x30', '/', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x32', '\x3', '\x2', '\x2', '\x2', '\x32', '\x34', 
		'\x5', '\x4', '\x3', '\b', '\x33', '.', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\x3', '\x2', '\x2', '\x2', '\x36', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x35', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x39', '\t', '\x2', '\x2', '\x2', '\x39', '\a', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\a', '!', '\x2', '\x2', ';', '\t', '\x3', '\x2', '\x2', 
		'\x2', '<', '?', '\x5', ' ', '\x11', '\x2', '=', '>', '\a', '\x5', '\x2', 
		'\x2', '>', '@', '\x5', '\x14', '\v', '\x2', '?', '=', '\x3', '\x2', '\x2', 
		'\x2', '?', '@', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x43', '\a', '\r', '\x2', '\x2', '\x42', '\x44', 
		'\x5', '\x10', '\t', '\x2', '\x43', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', 'J', '\x3', '\x2', 
		'\x2', '\x2', '\x45', '\x46', '\x5', ' ', '\x11', '\x2', '\x46', 'G', 
		'\x5', '\xE', '\b', '\x2', 'G', 'H', '\x5', '\x10', '\t', '\x2', 'H', 
		'J', '\x3', '\x2', '\x2', '\x2', 'I', '<', '\x3', '\x2', '\x2', '\x2', 
		'I', '\x45', '\x3', '\x2', '\x2', '\x2', 'J', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\t', '\x3', '\x2', '\x2', 'L', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\t', '\x4', '\x2', '\x2', 'N', '\xF', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\x5', '\x12', '\n', '\x2', 'P', '\x11', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'Y', '\a', '\a', '\x2', '\x2', 'R', 'Y', '\a', 
		'\b', '\x2', '\x2', 'S', 'Y', '\a', '\x6', '\x2', '\x2', 'T', 'Y', '\a', 
		'\x43', '\x2', '\x2', 'U', 'Y', '\a', '\t', '\x2', '\x2', 'V', 'Y', '\x5', 
		'\x16', '\f', '\x2', 'W', 'Y', '\a', '\x44', '\x2', '\x2', 'X', 'Q', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'R', '\x3', '\x2', '\x2', '\x2', 'X', 'S', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'T', '\x3', '\x2', '\x2', '\x2', 'X', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'Y', '\x13', '\x3', '\x2', '\x2', '\x2', 'Z', '[', 
		'\t', '\x5', '\x2', '\x2', '[', '\x15', '\x3', '\x2', '\x2', '\x2', '\\', 
		'\x61', '\x5', '\x18', '\r', '\x2', ']', '\x61', '\x5', '\x1A', '\xE', 
		'\x2', '^', '\x61', '\x5', '\x1C', '\xF', '\x2', '_', '\x61', '\x5', '\x1E', 
		'\x10', '\x2', '`', '\\', '\x3', '\x2', '\x2', '\x2', '`', ']', '\x3', 
		'\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', '\x2', '`', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x17', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\t', '\x6', '\x2', '\x2', '\x63', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x65', '\t', '\a', '\x2', '\x2', '\x65', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x66', 'g', '\t', '\b', '\x2', '\x2', 'g', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '\x42', '\x2', '\x2', 'i', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '\x44', '\x2', '\x2', 
		'k', '!', '\x3', '\x2', '\x2', '\x2', '\n', ',', '\x30', '\x35', '?', 
		'\x43', 'I', 'X', '`',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace TaskPrincess.FilterDsl.Antlr
